language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/activesupport-3.1.gemfile
  - gemfiles/activesupport-6.0.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/activesupport-6.0.gemfile
      rvm: 2.2
    - gemfile: gemfiles/activesupport-6.0.gemfile
      rvm: 2.3
    - gemfile: gemfiles/activesupport-6.0.gemfile
      rvm: 2.4
